package com.qinfenfeng.roadmeets.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Address implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.gmt_create
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.gmt_modified
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.longitude
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private BigDecimal longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.latitude
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private BigDecimal latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.name
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_detail
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private String addressDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.type
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.hot_point
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Integer hotPoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.deleted
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table address
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.gmt_create
     *
     * @return the value of address.gmt_create
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.gmt_create
     *
     * @param gmtCreate the value for address.gmt_create
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.gmt_modified
     *
     * @return the value of address.gmt_modified
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.gmt_modified
     *
     * @param gmtModified the value for address.gmt_modified
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.longitude
     *
     * @return the value of address.longitude
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.longitude
     *
     * @param longitude the value for address.longitude
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.latitude
     *
     * @return the value of address.latitude
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.latitude
     *
     * @param latitude the value for address.latitude
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.name
     *
     * @return the value of address.name
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.name
     *
     * @param name the value for address.name
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_detail
     *
     * @return the value of address.address_detail
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public String getAddressDetail() {
        return addressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_detail
     *
     * @param addressDetail the value for address.address_detail
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setAddressDetail(String addressDetail) {
        this.addressDetail = addressDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.type
     *
     * @return the value of address.type
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.type
     *
     * @param type the value for address.type
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.hot_point
     *
     * @return the value of address.hot_point
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Integer getHotPoint() {
        return hotPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.hot_point
     *
     * @param hotPoint the value for address.hot_point
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setHotPoint(Integer hotPoint) {
        this.hotPoint = hotPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.deleted
     *
     * @return the value of address.deleted
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.deleted
     *
     * @param deleted the value for address.deleted
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", name=").append(name);
        sb.append(", addressDetail=").append(addressDetail);
        sb.append(", type=").append(type);
        sb.append(", hotPoint=").append(hotPoint);
        sb.append(", deleted=").append(deleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}