package com.qinfenfeng.roadmeets.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class Friend implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.gmt_create
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.gmt_modified
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.user_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.friend_user_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Long friendUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.scene
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private String scene;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.deleted
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table friend
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.id
     *
     * @return the value of friend.id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.id
     *
     * @param id the value for friend.id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.gmt_create
     *
     * @return the value of friend.gmt_create
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.gmt_create
     *
     * @param gmtCreate the value for friend.gmt_create
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.gmt_modified
     *
     * @return the value of friend.gmt_modified
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.gmt_modified
     *
     * @param gmtModified the value for friend.gmt_modified
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.user_id
     *
     * @return the value of friend.user_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.user_id
     *
     * @param userId the value for friend.user_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.friend_user_id
     *
     * @return the value of friend.friend_user_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Long getFriendUserId() {
        return friendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.friend_user_id
     *
     * @param friendUserId the value for friend.friend_user_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setFriendUserId(Long friendUserId) {
        this.friendUserId = friendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.scene
     *
     * @return the value of friend.scene
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public String getScene() {
        return scene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.scene
     *
     * @param scene the value for friend.scene
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setScene(String scene) {
        this.scene = scene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.deleted
     *
     * @return the value of friend.deleted
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.deleted
     *
     * @param deleted the value for friend.deleted
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", userId=").append(userId);
        sb.append(", friendUserId=").append(friendUserId);
        sb.append(", scene=").append(scene);
        sb.append(", deleted=").append(deleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}