package com.qinfenfeng.roadmeets.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class Team implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.gmt_create
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.gmt_modified
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.creator
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.origin_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Long originId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.destination_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Long destinationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.target_time
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Date targetTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.finished
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Byte finished;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.scene
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private String scene;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team.deleted
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table team
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.id
     *
     * @return the value of team.id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.id
     *
     * @param id the value for team.id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.gmt_create
     *
     * @return the value of team.gmt_create
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.gmt_create
     *
     * @param gmtCreate the value for team.gmt_create
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.gmt_modified
     *
     * @return the value of team.gmt_modified
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.gmt_modified
     *
     * @param gmtModified the value for team.gmt_modified
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.creator
     *
     * @return the value of team.creator
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.creator
     *
     * @param creator the value for team.creator
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.origin_id
     *
     * @return the value of team.origin_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Long getOriginId() {
        return originId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.origin_id
     *
     * @param originId the value for team.origin_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setOriginId(Long originId) {
        this.originId = originId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.destination_id
     *
     * @return the value of team.destination_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Long getDestinationId() {
        return destinationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.destination_id
     *
     * @param destinationId the value for team.destination_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setDestinationId(Long destinationId) {
        this.destinationId = destinationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.target_time
     *
     * @return the value of team.target_time
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Date getTargetTime() {
        return targetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.target_time
     *
     * @param targetTime the value for team.target_time
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setTargetTime(Date targetTime) {
        this.targetTime = targetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.finished
     *
     * @return the value of team.finished
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Byte getFinished() {
        return finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.finished
     *
     * @param finished the value for team.finished
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setFinished(Byte finished) {
        this.finished = finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.scene
     *
     * @return the value of team.scene
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public String getScene() {
        return scene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.scene
     *
     * @param scene the value for team.scene
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setScene(String scene) {
        this.scene = scene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team.deleted
     *
     * @return the value of team.deleted
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team.deleted
     *
     * @param deleted the value for team.deleted
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", creator=").append(creator);
        sb.append(", originId=").append(originId);
        sb.append(", destinationId=").append(destinationId);
        sb.append(", targetTime=").append(targetTime);
        sb.append(", finished=").append(finished);
        sb.append(", scene=").append(scene);
        sb.append(", deleted=").append(deleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}