package com.qinfenfeng.roadmeets.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class TeamUserRel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_user_rel.id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_user_rel.gmt_create
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_user_rel.gmt_modified
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_user_rel.team_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Long teamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_user_rel.user_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_user_rel.type
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_user_rel.evaluate
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Byte evaluate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column team_user_rel.deleted
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table team_user_rel
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_user_rel.id
     *
     * @return the value of team_user_rel.id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_user_rel.id
     *
     * @param id the value for team_user_rel.id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_user_rel.gmt_create
     *
     * @return the value of team_user_rel.gmt_create
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_user_rel.gmt_create
     *
     * @param gmtCreate the value for team_user_rel.gmt_create
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_user_rel.gmt_modified
     *
     * @return the value of team_user_rel.gmt_modified
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_user_rel.gmt_modified
     *
     * @param gmtModified the value for team_user_rel.gmt_modified
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_user_rel.team_id
     *
     * @return the value of team_user_rel.team_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Long getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_user_rel.team_id
     *
     * @param teamId the value for team_user_rel.team_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setTeamId(Long teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_user_rel.user_id
     *
     * @return the value of team_user_rel.user_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_user_rel.user_id
     *
     * @param userId the value for team_user_rel.user_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_user_rel.type
     *
     * @return the value of team_user_rel.type
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_user_rel.type
     *
     * @param type the value for team_user_rel.type
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_user_rel.evaluate
     *
     * @return the value of team_user_rel.evaluate
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Byte getEvaluate() {
        return evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_user_rel.evaluate
     *
     * @param evaluate the value for team_user_rel.evaluate
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setEvaluate(Byte evaluate) {
        this.evaluate = evaluate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column team_user_rel.deleted
     *
     * @return the value of team_user_rel.deleted
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column team_user_rel.deleted
     *
     * @param deleted the value for team_user_rel.deleted
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_user_rel
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", teamId=").append(teamId);
        sb.append(", userId=").append(userId);
        sb.append(", type=").append(type);
        sb.append(", evaluate=").append(evaluate);
        sb.append(", deleted=").append(deleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}