package com.qinfenfeng.roadmeets.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class UserInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gmt_create
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gmt_modified
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nick_name
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.avatar_url
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gender
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.union_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private String unionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.open_id_min
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private String openIdMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.open_id_android
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private String openIdAndroid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phone_num
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private String phoneNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.deleted
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gmt_create
     *
     * @return the value of user_info.gmt_create
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gmt_create
     *
     * @param gmtCreate the value for user_info.gmt_create
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gmt_modified
     *
     * @return the value of user_info.gmt_modified
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gmt_modified
     *
     * @param gmtModified the value for user_info.gmt_modified
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nick_name
     *
     * @return the value of user_info.nick_name
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nick_name
     *
     * @param nickName the value for user_info.nick_name
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.avatar_url
     *
     * @return the value of user_info.avatar_url
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.avatar_url
     *
     * @param avatarUrl the value for user_info.avatar_url
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gender
     *
     * @return the value of user_info.gender
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gender
     *
     * @param gender the value for user_info.gender
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.union_id
     *
     * @return the value of user_info.union_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.union_id
     *
     * @param unionId the value for user_info.union_id
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.open_id_min
     *
     * @return the value of user_info.open_id_min
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public String getOpenIdMin() {
        return openIdMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.open_id_min
     *
     * @param openIdMin the value for user_info.open_id_min
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setOpenIdMin(String openIdMin) {
        this.openIdMin = openIdMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.open_id_android
     *
     * @return the value of user_info.open_id_android
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public String getOpenIdAndroid() {
        return openIdAndroid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.open_id_android
     *
     * @param openIdAndroid the value for user_info.open_id_android
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setOpenIdAndroid(String openIdAndroid) {
        this.openIdAndroid = openIdAndroid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.phone_num
     *
     * @return the value of user_info.phone_num
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.phone_num
     *
     * @param phoneNum the value for user_info.phone_num
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.deleted
     *
     * @return the value of user_info.deleted
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.deleted
     *
     * @param deleted the value for user_info.deleted
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Mon Jan 13 15:22:13 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", nickName=").append(nickName);
        sb.append(", avatarUrl=").append(avatarUrl);
        sb.append(", gender=").append(gender);
        sb.append(", unionId=").append(unionId);
        sb.append(", openIdMin=").append(openIdMin);
        sb.append(", openIdAndroid=").append(openIdAndroid);
        sb.append(", phoneNum=").append(phoneNum);
        sb.append(", deleted=").append(deleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}