package com.qinfenfeng.roadmeets.mbg.mapper;

import com.qinfenfeng.roadmeets.mbg.model.Friend;
import com.qinfenfeng.roadmeets.mbg.model.FriendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Sun Feb 09 15:58:55 CST 2020
     */
    int countByExample(FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Sun Feb 09 15:58:55 CST 2020
     */
    int deleteByExample(FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Sun Feb 09 15:58:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Sun Feb 09 15:58:55 CST 2020
     */
    int insert(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Sun Feb 09 15:58:55 CST 2020
     */
    int insertSelective(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Sun Feb 09 15:58:55 CST 2020
     */
    List<Friend> selectByExample(FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Sun Feb 09 15:58:55 CST 2020
     */
    Friend selectByPrimaryKey(Integer id);

    /**
     * 根据场景值获得用户
     * @param friend
     * @return
     */
    int selectByScene(Friend friend);

    List<Friend> selectByUserId(Long userId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Sun Feb 09 15:58:55 CST 2020
     */
    int updateByExampleSelective(@Param("record") Friend record, @Param("example") FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Sun Feb 09 15:58:55 CST 2020
     */
    int updateByExample(@Param("record") Friend record, @Param("example") FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Sun Feb 09 15:58:55 CST 2020
     */
    int updateByPrimaryKeySelective(Friend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend
     *
     * @mbggenerated Sun Feb 09 15:58:55 CST 2020
     */
    int updateByPrimaryKey(Friend record);
}