server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://47.98.41.124:3307/road_meet?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
    #    schema:
    #      - classpath: sql/department.sql
    #      - classpath: sql/employee.sql
    #    initialization-mode: always
  redis:
    host: 47.98.41.124
    password: 123456
    port: 6379
    # 连接池最大连接数（使用负值表示没有限制）
  cache:
    type: redis

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml


secretKey: 7786df7fc3a34e26a61c034d5ec8245d

TokenPassTime: 604800000
# 微信配置
weixin:
#  appID: wx04659b17ae69b0ac
#  secret: 0ff0371e5da59df24d4292397ace8294
   appID: wx8e72c0c098dad0c8
   secret: cd2c367c501588233d4c94e419760882

Team:
  passTime: 7 # 行程过期时间，单位：天
  distance: 3 # 多少范围内的订单推送

# 信鸽配置
xinge:
  appID: aed49ff8f26ab
  secretKey: 30381cf109841f308092485db17f353f
logging:
  level:
    com:
      qinfenfeng:
        roadmeets:
          mbg:
            mapper: debug
